// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
#include "Robot.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
DriveBase* Robot::driveBase = 0;
Stacker* Robot::stacker = 0;
Grabber* Robot::grabber = 0;
OI* Robot::oi = 0;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INITIALIZATION
PowerDistributionPanel* Robot::pdp = 0;
StackerControlTask* Robot::stackerControl = 0;
SqueezeControlTask* Robot::squeezeControl = 0;

void Robot::RobotInit() {
	RobotMap::init();
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveBase = new DriveBase();
	stacker = new Stacker();
	grabber = new Grabber();

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	// This MUST be here. If the OI creates Commands (which it very likely
	// will), constructing it during the construction of CommandBase (from
	// which commands extend), subsystems are not guaranteed to be
	// yet. Thus, their requires() statements may grab null pointers. Bad
	// news. Don't move it.
	oi = new OI();
	lw = LiveWindow::GetInstance();

	// instantiate the command used for the autonomous period
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
	File = RAWCConstants::getInstance();
	driveBase->SetWheelbase(19.5/2, 28.0, 19.5/2);
	FLOffset = File->getValueForKey("FLOff");
	FROffset = File->getValueForKey("FROff");
	RLOffset = File->getValueForKey("RLOff");
	RROffset = File->getValueForKey("RROff");
	driveBase->SetOffsets(FLOffset, FROffset, RLOffset, RROffset);

	driveBase->frontLeft->Enable();
	driveBase->frontRight->Enable();
	driveBase->rearLeft->Enable();
	driveBase->rearRight->Enable();

	pdp=new PowerDistributionPanel();

	pressed5 = false;
	pressed7 = false;
	liftUsingJoystick = false;

	dartPos1 = 460;
	dartPos2 = 333;
	containerPickupPosition = 90;
	autoTotePickupPos = 625;
	toteDropPosition = 409;
	dartClosedLoop = true;

	stackerControl = new StackerControlTask();
	stackerControl->Start();
	squeezeControl = new SqueezeControlTask();
	squeezeControl->Start();

	autoRightUSDistanceToWall = 79;
	onTargetCounter = 0;

	autoChooser = new SendableChooser();
	autoChooser->AddDefault("01. 3TotePickup", (void*)ThreeTotePickup);
	autoChooser->AddObject("02. Test3TotePikcup", (void*)Test3TotePickup);
	SmartDashboard::PutData("Autonomous Chooser", autoChooser);
  }

void Robot::DisabledInit(){

}

void Robot::DisabledPeriodic() {
	Scheduler::GetInstance()->Run();

	cout << "Periodic Cycle Time: "<< GetClock() - prevCycleTime << endl;
	prevCycleTime = GetClock();


	/*******************SmartDashboard*********************/
	if(oi->getDriverRight()->GetRawButton(7))
		StackerSMDB();
	if(oi->getDriverRight()->GetRawButton(8))
		DriveBaseSMDB();
	if(oi->getDriverRight()->GetRawButton(9))
		SystemSMDB();

}

void Robot::AutonomousInit() {
    autoProgram = static_cast<AutoProgram>((int)(autoChooser->GetSelected()));
    genericAutoProgram.clear();
	switch(autoProgram) {
	case ThreeTotePickup:
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(WaitForLift);
		genericAutoProgram.push_back(MoveDartToVertical);
		genericAutoProgram.push_back(WaitForDart);
		genericAutoProgram.push_back(FirstMove);
		genericAutoProgram.push_back(TurnTo40);
		genericAutoProgram.push_back(CrabToFirstTote);
		genericAutoProgram.push_back(DriveForwardToFirstTote);
		genericAutoProgram.push_back(SquareToWall);
		genericAutoProgram.push_back(DriveForwardToTote);
		//genericAutoProgram.push_back(CenterTote);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveForward15);
		genericAutoProgram.push_back(DriveForwardToTote);
		//genericAutoProgram.push_back(CenterTote);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveForward15);
		genericAutoProgram.push_back(DriveForwardToTote);
		//genericAutoProgram.push_back(CenterTote);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveToBump);
		genericAutoProgram.push_back(DriveOffBump);
		genericAutoProgram.push_back(DriveAwayFromBump);
		genericAutoProgram.push_back(DropTotes);
		genericAutoProgram.push_back(BackAwayFromTotes);
		genericAutoProgram.push_back(End);
		break;

	case Test3TotePickup:
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveForwardToTote);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveForwardToTote);
		genericAutoProgram.push_back(IndexUp);
		genericAutoProgram.push_back(DriveToBump);
		genericAutoProgram.push_back(DropTotes);
		genericAutoProgram.push_back(End);
		break;
	}
	autoStepIncrementer = 0;
	autoStep = genericAutoProgram[autoStepIncrementer];
//	autoStepTimer->Reset();
	autoStepTime = GetClock();
	onTargetCounter = 0;
	robotAngle = 0;
	driveBase->imu->ZeroYaw();
}

void Robot::AutonomousPeriodic() {
	float x = 0;
	float y = 0;
	float twist = 0;
	bool useDriveParams;

	switch(autoStep) {

	case IndexUp:
		SmartDashboard::PutString("AutoStep", "IndexUp");
		x = 0;
		y = 0;
		useDriveParams = true;
		stackerControl->IncLiftPosition();
		autoStepComplete = true;
		break;

	case WaitForLift:
		SmartDashboard::PutString("AutoStep", "WaitForLift");
		x = 0;
		y = 0;
		useDriveParams = true;
		if(fabs(stackerControl->GetError()) < 1000 && stacker->squeeze->Get() == 0) {
			autoStepComplete = true;
		}
		break;

	case MoveDartToVertical:
		SmartDashboard::PutString("AutoStep", "MoveDartToVertical");
		x = 0;
		y = 0;
		useDriveParams = true;
		stacker->dart->SetControlMode(CANSpeedController::kPosition);
		stacker->dart->Set(autoTotePickupPos);
		autoStepComplete = true;
		break;

	case WaitForDart:
		SmartDashboard::PutString("AutoStep", "WaitForDart");
		x = 0;
		y = 0;
		useDriveParams = true;
		if(stacker->dart->GetPosition() > dartPos1) {
			autoStepComplete = true;
		}
		break;


	case FirstMove:
		SmartDashboard::PutString("AutoStep", "FirstMove");
		x = .2;
		y = .4;
		robotAngle = -20;
		useDriveParams = true;
		driveBase->DriveControlTwist->SetPID(.035, 0, .25);
		if(GetClock() - autoStepTime > 1.0) {
			autoStepComplete = true;
		}
		break;

	case DriveForwardToFirstTote:
		SmartDashboard::PutString("AutoStep", "DriveForwardToFirstTote");
		x = 0;
		y = .4;
		robotAngle = 0;
		useDriveParams = true;
		driveBase->DriveControlTwist->SetPID(.035, 0, .25);
		if(GetClock() - autoStepTime > .3) {
			autoStepComplete = true;
		}
		break;

	case DriveForward15:
		SmartDashboard::PutString("AutoStep", "DriveForward15");
		x = -.01*(autoRightUSDistanceToWall - driveBase->rightUS->GetDistance1());
		if (x<-.1)
			x=-.1;
		if (x>.1)
			x=.1;
		y = .4;
		robotAngle = 0;
		useDriveParams = true;
		driveBase->DriveControlTwist->SetPID(.001, 0, .15);
		if(GetClock() - autoStepTime > 1.5) {
			autoStepComplete = true;
		}

		break;
//sup dude
	case TurnTo40:
		SmartDashboard::PutString("AutoStep", "TurnTo40");
		x = 0;
		y = 0;
		robotAngle = -40;
		useDriveParams = true;
		driveBase->DriveControlTwist->SetPID(.05, 0, .25);
		if(driveBase->DriveControlTwist->OnTarget()) {
			onTargetCounter++;
			if(onTargetCounter > 5) {
				autoStepComplete = true;
				driveBase->imu->ZeroYaw();
				robotAngle = 0;
			}
		}
			break;

	case SquareToWall:
		SmartDashboard::PutString("AutoStep", "SquareToWall");
		x = 0;
		y = 0;
		useDriveParams = false;
		twist =.05*(driveBase->rightUS->GetDistance1() - driveBase->rightUS->GetDistance2());
		if (twist<-.2)
			twist=-.2;
		if (twist>.2)
			twist=.2;
		driveBase->Crab(twist, y, x, false);
		if(fabs(driveBase->rightUS->GetDistance1() - driveBase->rightUS->GetDistance2()) < 2) {
			onTargetCounter++;
			if(onTargetCounter > 10) {
				autoStepComplete = true;
				driveBase->imu->ZeroYaw();
				robotAngle = 0;
			}
		}

		break;


	case CrabToFirstTote:
		SmartDashboard::PutString("AutoStep", "CrabToFirstTote");
		driveBase->DriveControlTwist->SetPID(.0005, 0, 0);
		x = -.05*(autoRightUSDistanceToWall - driveBase->rightUS->GetDistance1());
		if (x<-.2)
			x=-.2;
		if (x>.2)
			x=.2;
		y = 0;
		useDriveParams = true;
		if(fabs(autoRightUSDistanceToWall - driveBase->rightUS->GetDistance1()) < 3) {
			onTargetCounter++;
			if(onTargetCounter > 5) {
				autoStepComplete = true;
			}
		}
			break;

	case DriveForwardToTote:
		SmartDashboard::PutString("AutoStep", "DriveForwardToTote");
		x = -.01*(autoRightUSDistanceToWall - driveBase->rightUS->GetDistance1());
		if (x<-.1)
			x=-.1;
		if (x>.1)
			x=.1;
		y = 0.2;
		useDriveParams = true;
		driveBase->DriveControlTwist->SetPID(.001, 0, .15);
		if((GetClock() - autoStepTime > .5) && (!driveBase->toteWideLeft->Get() || driveBase->toteWideRight->Get())) {
			autoStepComplete = true;
		}
		break;

	case CenterTote:
		SmartDashboard::PutString("AutoStep", "CenterTote");
		if(!driveBase->toteWideLeft->Get() || !driveBase->toteWideRight->Get()) {
			useDriveParams = false;
			float twist = 0;
			if (!driveBase->toteWideLeft->Get())
				twist = -.15;
			if (!driveBase->toteWideRight->Get())
				twist = .15;
			driveBase->Crab(twist,0,0,true);
			}
		else {
			x = 0;
			y = .1;
			useDriveParams = true;
		}
		if(!driveBase->toteWideLeft->Get() && !driveBase->toteWideRight->Get())
			autoStepComplete = true;
		break;

	case DriveToBump:
		SmartDashboard::PutString("AutoStep", "DriveToBump");
		x = -.5;
		y = 0;
		useDriveParams = true;
		if(driveBase->imu->GetRoll() > 3)
			autoStepComplete = true;
		break;

	case DriveOffBump:
		SmartDashboard::PutString("AutoStep", "DrivePastBump");
		x = -.5;
		y = 0;
		useDriveParams = true;
		if(driveBase->imu->GetRoll() < -3) {
			autoStepComplete = true;
			stacker->dart->Set(toteDropPosition);
		}
		break;

	case DriveAwayFromBump:
		SmartDashboard::PutString("AutoStep", "DriveAwayFromBump");
		x = -.5;
		y = 0;
		useDriveParams = true;
		if(GetClock() - autoStepTime > .5) {
			autoStepComplete = true;
			squeezeControl->Open();
		}
		break;


	case DropTotes:
		SmartDashboard::PutString("AutoStep", "DropTotes");
		x = 0;
		y = -.2;
		useDriveParams = true;
		stackerControl->LiftOpenLoop(-.2);
		if(GetClock() - autoStepTime > 1.5)
			autoStepComplete = true;
		break;

	case BackAwayFromTotes:
		SmartDashboard::PutString("AutoStep", "BackAwayFromTotes");
		x = 0;
		y = -.4;
		useDriveParams = true;
		if(GetClock() - autoStepTime > .6)
			autoStepComplete = true;
		break;



	case End:
		SmartDashboard::PutString("AutoStep", "End");
		x = 0;
		y = 0;
		useDriveParams = true;
	}

	if(useDriveParams) {
		driveBase->DriveControlTwist->SetSetpoint(robotAngle);
		driveBase->Crab(driveBase->CrabSpeedTwist->Get(), y, x, true);
	}

	/***********************Increment Through Program****************************/
	if (autoStepComplete) {
		autoStepTime = GetClock();
		//autoStepTimer->Reset();
		autoStepComplete = false;
		autoStepIncrementer ++;
		autoStep = genericAutoProgram.at(autoStepIncrementer);
	}
}

void Robot::TeleopInit() {

}

void Robot::TeleopPeriodic() {
//	cout << "Periodic Cycle Time: "<< GetClock() - prevCycleTime << endl;
//	prevCycleTime = GetClock();

	/*******************SmartDashboard*********************/
	if(oi->getDriverRight()->GetRawButton(7))
		StackerSMDB();
	if(oi->getDriverRight()->GetRawButton(8))
		DriveBaseSMDB();
	if(oi->getDriverRight()->GetRawButton(9))
		SystemSMDB();
	/**************DRIVEBASE************************/

	//Resets gyro to zero when crab starts
	if (!prevTrigger && oi->getDriverRight()->GetRawButton(1)) {
		driveBase->imu->ZeroYaw();
	}

	prevTrigger = oi->getDriverRight()->GetRawButton(1);

	if(oi->getDriverLeft()->GetRawButton(7)) {
		float twist = 0;
		if(!driveBase->toteWideLeft->Get() || !driveBase->toteWideRight->Get()) {
			if (!driveBase->toteWideLeft->Get())
				twist = -.15;
			if (!driveBase->toteWideRight->Get())
				twist = .15;
			driveBase->Crab(twist,-oi->getJoystickY(),oi->getJoystickX(),true);
		}
		else
			driveBase->Crab(0,-oi->getJoystickY(),oi->getJoystickX(),true);

	}
	else {
		if(oi->getDriverLeft()->GetRawButton(1) && oi->getDriverRight()->GetMagnitude() < .1)
		{
			driveBase->Lock();
		}
		else if(oi->getDriverRight()->GetRawButton(1))
		{
			driveBase->Crab(oi->getJoystickTwist(),-oi->getJoystickY(),oi->getJoystickX(),true);
		}
		else if (oi->getDriverRight()->GetRawButton(2)) {
			driveBase->Steer(3.14159,oi->getDriverLeft()->GetX(),2.1);
		}
		else
		{
			driveBase->Steer(oi->getLeftJoystickXRadians(),oi->getJoystickY(),0.5);
		}
	}


	/**************STACKER************************/

	if((oi->getGamePad()->GetRawButton(6) || oi->getGamePad()->GetRawButton(8))) {

		if (!dartClosedLoop) {
			dartClosedLoop = true;
			stacker->dart->SetControlMode(CANSpeedController::kPosition);
		}

		if(oi->getGamePad()->GetRawButton(6))
			stacker->dart->Set(dartPos1);

		else if(oi->getGamePad()->GetRawButton(8))
			stacker->dart->Set(dartPos2);
	}

	else if (fabs(oi->getGamePad()->GetRawAxis(3)) > .1) {
		if (dartClosedLoop) {
			dartClosedLoop = false;
			stacker->dart->SetControlMode(CANSpeedController::kPercentVbus);
		}
		stacker->dart->Set(oi->getGamePad()->GetRawAxis(3));
	}

	else if(!dartClosedLoop)
		stacker->dart->Set(0);




	if(oi->getGamePad()->GetRawButton(5)) {
		if (!pressed5) {
		stackerControl->IncLiftPosition();
		pressed5 = true;
		}
	}
	else
		pressed5 = false;

	if (oi->getGamePad()->GetRawButton(7)) {
		if (!pressed7) {
			stackerControl->DecLiftPoistion();
			pressed7 = true;
			}
	}
	else
		pressed7 = false;

	if (oi->getGamePad()->GetPOV(0) == 180) {
		stackerControl->Home();

		if (!dartClosedLoop) {
			dartClosedLoop = true;
			stacker->dart->SetControlMode(CANSpeedController::kPosition);
		}
		stacker->dart->Set(containerPickupPosition);

	}

	if (fabs(oi->getGamePad()->GetRawAxis(1)) > .1) {
		stackerControl->LiftOpenLoop(-oi->getScaledJoystick(oi->getGamePad()->GetRawAxis(1),3));
		liftUsingJoystick = true;
	}
	else if(liftUsingJoystick) {
		stackerControl->LiftOpenLoop(0);
		liftUsingJoystick = false;
	}

/*
	if(oi->getGamePad()->GetRawButton(4))
		stacker->liftFrontRight->Set(.6);
	else if (oi->getGamePad()->GetRawButton(2))
		stacker->liftFrontRight->Set(-.6);
	else
		stacker->liftFrontRight->Set(0);
*/

//	if(!stackerControl->GetHoming() && stackerControl->Geti() != 1)
//		stacker->squeeze->Set(oi->getGamePad()->GetRawAxis(0)/2);

	if(oi->getGamePad()->GetPOV() == 270)
		squeezeControl->Close(false);
	if(oi->getGamePad()->GetPOV() == 90)
		squeezeControl->Open();

	/**************GRABBER************************/

	grabber->extension->Set(oi->getGamePad()->GetRawAxis(2));

}

void Robot::TestPeriodic() {
	lw->Run();
}

void Robot::SystemSMDB() {
	SmartDashboard::PutNumber("FrontLeftSteerCurrentPDP",pdp->GetCurrent(10));
	SmartDashboard::PutNumber("FrontRightSteerCurentPDP",pdp->GetCurrent(5));
	SmartDashboard::PutNumber("FrontLeftDriveCurrentPDP",pdp->GetCurrent(14));
	SmartDashboard::PutNumber("FrontRightDriveCurrentPDP",pdp->GetCurrent(1));
	SmartDashboard::PutNumber("SqueezerCurrent", pdp->GetCurrent(9));

}

void Robot::DriveBaseSMDB() {
	SmartDashboard::PutNumber("IMUYaw",driveBase->imu->GetYaw());
	SmartDashboard::PutNumber("IMUPitch",driveBase->imu->GetPitch());
	SmartDashboard::PutNumber("IMURoll",driveBase->imu->GetRoll());
	SmartDashboard::PutNumber("FrontLeftSteerCurrent",driveBase->frontRightSteer->GetOutputCurrent());
	SmartDashboard::PutNumber("frontleftvolt",driveBase->frontLeftPos->GetAverageVoltage());
	SmartDashboard::PutNumber("rearleftvolt",driveBase->rearLeftPos->GetAverageVoltage());
	SmartDashboard::PutNumber("frontrightvolt",driveBase->frontRightPos->GetAverageVoltage());
	SmartDashboard::PutBoolean("ToteWideLeftB", driveBase->toteWideLeft->Get());
	SmartDashboard::PutBoolean("ToteNarrowLeftB", driveBase->toteNarrowLeft->Get());
	SmartDashboard::PutBoolean("ToteCenterB", driveBase->toteCenter->Get());
	SmartDashboard::PutBoolean("ToteNarrowRightB", driveBase->toteNarrowRight->Get());
	SmartDashboard::PutBoolean("ToteWideRightB", driveBase->toteWideRight->Get());
//	SmartDashboard::PutNumber("UltrasonicDistanceFrontt", driveBase->frontUS->GetDistance());
	SmartDashboard::PutNumber("UltrasonicDistanceRight1", driveBase->rightUS->GetDistance1());
	SmartDashboard::PutNumber("UltrasonicDistanceRight2", driveBase->rightUS->GetDistance2());

}

void Robot::StackerSMDB() {
	SmartDashboard::PutNumber("DartPosition",stacker->dart->GetAnalogIn());
	SmartDashboard::PutNumber("LitPosition",stacker->liftFrontLeft->GetEncPosition());
	SmartDashboard::PutNumber("SqueezePosition", stacker->squeezePosition->GetDistance());
	SmartDashboard::PutNumber("SqueezeRawPosition", stacker->squeezePosition->GetRaw());
	SmartDashboard::PutBoolean("StackerHomeSwitch", stacker->home->Get());
	SmartDashboard::PutNumber("SqueezeOutput", stacker->squeeze->Get());
	SmartDashboard::PutNumber("LiftPosition", stacker->liftFrontRight->GetPosition());
	SmartDashboard::PutNumber("LiftError", stackerControl->GetError());
	SmartDashboard::PutNumber("i", stackerControl->Geti());
	SmartDashboard::PutBoolean("StackerHoming", stackerControl->GetHoming());
	SmartDashboard::PutBoolean("DartForwardLimitSwitch", Robot::stacker->dart->GetForwardLimitOK());
	SmartDashboard::PutBoolean("DartReverseLimitSwitch", Robot::stacker->dart->GetReverseLimitOK());
}

START_ROBOT_CLASS(Robot);

